Fix for bug causing an error trace when a query was executed (with cache on) using conditions created using EntityConditionBuilder:
java.lang.UnsupportedOperationException: hashCode: org.ofbiz.entity.condition.EntityConditionBuilder$ConditionHolder
     [java] java.lang.UnsupportedOperationException: hashCode: org.ofbiz.entity.condition.EntityConditionBuilder$ConditionHolder

Thanks to Deepak Dixit for the bug report and for his tests.



git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1665154 13f79535-47bb-0310-9956-ffa450edef68