Applied patch from jira issue - OFBIZ-5844 - Convert java files to EntityQuery. ================================================================ Ashish Vijaywargiya / Arun Patidar: Getting error on http://demo-trunk-ofbiz.apache.org/ecommerce/round-gizmo-GZ-2644-p due to commit revision r1641044. There is an issue in CatalogUrlFilter class. Attaching the patch to fix the problem. Here is the error for your quick reference;
java.lang.IllegalArgumentException: You must pass an even sized array to the toMap method (size = 1)
	org.ofbiz.base.util.UtilMisc.toMap(UtilMisc.java:158)
	org.ofbiz.entity.util.EntityQuery.where(EntityQuery.java:160)
	org.ofbiz.product.category.CatalogUrlFilter.doFilter(CatalogUrlFilter.java:97)
================================================================ 
Thanks Rishi for the contribution.

git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1642104 13f79535-47bb-0310-9956-ffa450edef68