Fixes a data type issue introduced recently (works in R10.04 and R9.04). I did not take the time to analysis the problem further, but I expect the same issue may appear with the same condition: ie a DB field type NUMERIC and an entity.field of type Integer used in a service, switching to Long lazily solves the issue.
Actually in R10.04 the problem is reported as a warning but the service is not rolled back. Not sure if it's a desired change (then how to use Integer as field type in an entity also used by a service?)

GenericEntity.java:426:WARN ]
---- exception report ----------------------------------------------------------
=-=-=-=-=-=-=-=-= Database type warning GenericEntity.set =-=-=-=-=-=-=-=-= In entity field [ProtectedView.maxHits] set the value passed in [java.lang.Integer] is not compatible with the Java type of the fiel
d [Long]
Exception: java.lang.Exception
Message: Location of database type warning
---- stack trace ---------------------------------------------------------------
java.lang.Exception: Location of database type warning
org.ofbiz.entity.GenericEntity.set(GenericEntity.java:426)
org.ofbiz.entity.GenericEntity.set(GenericEntity.java:372)
org.ofbiz.entity.GenericEntity.setAllFields(GenericEntity.java:906)
org.ofbiz.entity.GenericEntity.setNonPKFields(GenericEntity.java:862)
org.ofbiz.service.engine.EntityAutoEngine.runSync(EntityAutoEngine.java:235)
org.ofbiz.service.ModelServiceReader$GenericInvokerImpl.runSync(ModelServiceReader.java:832)
_$gen.file_58$.D_58$.workspace.ofbizDev.framework.common.servicedef.services_95$security_46$xml_35$addProtectedViewToSecurityGroup.runSync(file:/D:/workspace/ofbizDev/framework/common/servicedef/services_secu
rity.xml#addProtectedViewToSecurityGroup:95)


git-svn-id: https://svn.apache.org/repos/asf/ofbiz/trunk@1099388 13f79535-47bb-0310-9956-ffa450edef68